import Head from 'next/head'
import Image from 'next/image'
import NavBar from '../Components/NavBar/NavBar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Star Admin2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div style={{backgroundColor: "#F4F5F7"}}>
        <NavBar />
      </div>


      
    </div>
  )
}
