import Head from 'next/head'
import Image from 'next/image'
import NavBar from '../Components/NavBar/NavBar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Star Admin2 main</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <NavBar />
      <div className={styles.pageTitle}>
        <h1>Dashboard Page</h1>
      </div>
    </div>
  )
}
